; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--cpp --split_sections --debug -c -S -o.\objects\abi.s --depend=.\objects\abi.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\abi.crf cores\abi.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.__cxa_deleted_virtual||, CODE, READONLY, ALIGN=1

__cxa_deleted_virtual PROC
        NOP      
|L0.2|
        B        |L0.2|
        ENDP


        AREA ||i.__cxa_pure_virtual||, CODE, READONLY, ALIGN=1

__cxa_pure_virtual PROC
        NOP      
|L1.2|
        B        |L1.2|
        ENDP


        AREA ||.ARM.exidx||, LINKORDER=||i.__cxa_pure_virtual||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||i.__cxa_pure_virtual||
        DCD      0x00000001

        AREA ||area_number.3||, LINKORDER=||i.__cxa_deleted_virtual||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.3||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i.__cxa_deleted_virtual||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT __cxa_deleted_virtual [CODE]
        EXPORT __cxa_pure_virtual [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
