; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--cpp --split_sections --debug -c -S -o.\objects\stream.s --depend=.\objects\stream.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\stream.crf cores\Stream.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.NOPS_FOR_USEC||, CODE, READONLY, ALIGN=1

NOPS_FOR_USEC PROC
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        BX       lr
        ENDP


        AREA ||i._ZN6Stream10parseFloatE13LookaheadModec||, CODE, READONLY, ALIGN=2

_ZN6Stream10parseFloatE13LookaheadModec PROC
        PUSH     {r4-r10,lr}
        VPUSH    {d8-d10}
        MOV      r8,r0
        MOV      r10,r1
        MOV      r6,r2
        MOV      r9,#0
        MOVS     r7,#0
        MOVS     r5,#0
        VMOV.F32 s0,#1.00000000
        VMOV.F32 s16,s0
        MOVS     r2,#1
        MOV      r1,r10
        MOV      r0,r8
        BL       _ZN6Stream13peekNextDigitE13LookaheadModeb
        MOV      r4,r0
        CMP      r4,#0
        BGE      |L1.58|
        VLDR     s0,|L1.212|
|L1.50|
        VPOP     {d8-d10}
        POP      {r4-r10,pc}
|L1.58|
        NOP      
|L1.60|
        CMP      r4,r6
        BEQ      |L1.140|
        CMP      r4,#0x2d
        BNE      |L1.74|
        MOV      r9,#1
        B        |L1.140|
|L1.74|
        CMP      r4,#0x2e
        BNE      |L1.82|
        MOVS     r7,#1
        B        |L1.140|
|L1.82|
        CMP      r4,#0x30
        BLT      |L1.140|
        CMP      r4,#0x39
        BGT      |L1.140|
        ADD      r0,r5,r5,LSL #2
        ADD      r0,r4,r0,LSL #1
        SUB      r5,r0,#0x30
        CBZ      r7,|L1.140|
        VMOV     r0,s16
        BL       __aeabi_f2d
        VMOV     d10,r0,r1
        VLDR     d0,|L1.216|
        VMOV     r2,r3,d0
        BL       __aeabi_dmul
        VMOV     d9,r0,r1
        BL       __aeabi_d2f
        VMOV     s16,r0
|L1.140|
        LDR      r0,[r8,#0]
        LDR      r1,[r0,#0xc]
        MOV      r0,r8
        BLX      r1
        MOV      r0,r8
        BL       _ZN6Stream9timedPeekEv
        MOV      r4,r0
        CMP      r4,#0x30
        BLT      |L1.166|
        CMP      r4,#0x39
        BLE      |L1.60|
|L1.166|
        CMP      r4,#0x2e
        BNE      |L1.174|
        CMP      r7,#0
        BEQ      |L1.60|
|L1.174|
        CMP      r4,r6
        BEQ      |L1.60|
        CMP      r9,#0
        BEQ      |L1.186|
        RSBS     r5,r5,#0
|L1.186|
        CBZ      r7,|L1.202|
        VMOV     s0,r5
        VCVT.F32.S32 s0,s0
        VMUL.F32 s0,s0,s16
        B        |L1.50|
|L1.202|
        VMOV     s0,r5
        VCVT.F32.S32 s0,s0
        B        |L1.50|
        ENDP

|L1.212|
        DCFS     0x00000000 ; 0
|L1.216|
        DCFD     0x3fb999999999999a ; 0.10000000000000001

        AREA ||i._ZN6Stream10readStringEv||, CODE, READONLY, ALIGN=2

_ZN6Stream10readStringEv PROC
        PUSH     {r4-r6,lr}
        MOV      r6,r0
        MOV      r4,r1
        ADR      r1,|L2.48|
        MOV      r0,r6
        BL       _ZN6StringC1EPKc
        MOV      r6,r0
        MOV      r0,r4
        BL       _ZN6Stream9timedReadEv
        MOV      r5,r0
        B        |L2.42|
|L2.26|
        UXTB     r1,r5
        MOV      r0,r6
        BL       _ZN6StringpLEc
        MOV      r0,r4
        BL       _ZN6Stream9timedReadEv
        MOV      r5,r0
|L2.42|
        CMP      r5,#0
        BGE      |L2.26|
        POP      {r4-r6,pc}
        ENDP

|L2.48|
        DCB      0
        DCB      0
        DCB      0
        DCB      0

        AREA ||i._ZN6Stream10setTimeoutEm||, CODE, READONLY, ALIGN=1

_ZN6Stream10setTimeoutEm PROC
        STR      r1,[r0,#8]
        BX       lr
        ENDP


        AREA ||i._ZN6Stream13peekNextDigitE13LookaheadModeb||, CODE, READONLY, ALIGN=1

_ZN6Stream13peekNextDigitE13LookaheadModeb PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        B        |L4.112|
|L4.12|
        MOV      r0,r5
        BL       _ZN6Stream9timedPeekEv
        MOV      r4,r0
        CMP      r4,#0
        BLT      |L4.42|
        CMP      r4,#0x2d
        BEQ      |L4.42|
        CMP      r4,#0x30
        BLT      |L4.36|
        CMP      r4,#0x39
        BLE      |L4.42|
|L4.36|
        CBZ      r7,|L4.48|
        CMP      r4,#0x2e
        BNE      |L4.48|
|L4.42|
        MOV      r0,r4
|L4.44|
        POP      {r4-r8,pc}
|L4.48|
        CBZ      r6,|L4.100|
        CMP      r6,#1
        BEQ      |L4.60|
        CMP      r6,#2
        BNE      |L4.102|
        B        |L4.66|
|L4.60|
        MOV      r0,#0xffffffff
        B        |L4.44|
|L4.66|
        CMP      r4,#9
        BEQ      |L4.84|
        CMP      r4,#0xa
        BEQ      |L4.88|
        CMP      r4,#0xd
        BEQ      |L4.86|
        CMP      r4,#0x20
        BNE      |L4.90|
        NOP      
|L4.84|
        NOP      
|L4.86|
        NOP      
|L4.88|
        B        |L4.96|
|L4.90|
        MOV      r0,#0xffffffff
        B        |L4.44|
|L4.96|
        NOP      
        NOP      
|L4.100|
        NOP      
|L4.102|
        NOP      
        LDR      r0,[r5,#0]
        LDR      r1,[r0,#0xc]
        MOV      r0,r5
        BLX      r1
|L4.112|
        B        |L4.12|
        ENDP


        AREA ||i._ZN6Stream14readBytesUntilEcPcj||, CODE, READONLY, ALIGN=1

_ZN6Stream14readBytesUntilEcPcj PROC
        PUSH     {r4-r10,lr}
        MOV      r9,r0
        MOV      r8,r1
        MOV      r5,r2
        MOV      r6,r3
        CBNZ     r6,|L5.20|
        MOVS     r0,#0
|L5.16|
        POP      {r4-r10,pc}
|L5.20|
        MOVS     r4,#0
        B        |L5.50|
|L5.24|
        MOV      r0,r9
        BL       _ZN6Stream9timedReadEv
        MOV      r7,r0
        CMP      r7,#0
        BLT      |L5.40|
        CMP      r7,r8
        BNE      |L5.42|
|L5.40|
        B        |L5.54|
|L5.42|
        STRB     r7,[r5],#1
        ADDS     r4,r4,#1
        NOP      
|L5.50|
        CMP      r4,r6
        BCC      |L5.24|
|L5.54|
        NOP      
        MOV      r0,r4
        B        |L5.16|
        ENDP


        AREA ||i._ZN6Stream15readStringUntilEc||, CODE, READONLY, ALIGN=2

_ZN6Stream15readStringUntilEc PROC
        PUSH     {r4-r8,lr}
        MOV      r7,r0
        MOV      r5,r1
        MOV      r6,r2
        ADR      r1,|L6.60|
        MOV      r0,r7
        BL       _ZN6StringC1EPKc
        MOV      r7,r0
        MOV      r0,r5
        BL       _ZN6Stream9timedReadEv
        MOV      r4,r0
        B        |L6.46|
|L6.30|
        UXTB     r1,r4
        MOV      r0,r7
        BL       _ZN6StringpLEc
        MOV      r0,r5
        BL       _ZN6Stream9timedReadEv
        MOV      r4,r0
|L6.46|
        CMP      r4,#0
        BLT      |L6.54|
        CMP      r4,r6
        BNE      |L6.30|
|L6.54|
        POP      {r4-r8,pc}
        ENDP

        DCW      0x0000
|L6.60|
        DCB      0
        DCB      0
        DCB      0
        DCB      0

        AREA ||i._ZN6Stream4findEPc||, CODE, READONLY, ALIGN=1

_ZN6Stream4findEPc PROC
        PUSH     {r3-r7,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOV      r0,r4
        BL       strlen
        MOV      r6,r0
        MOVS     r0,#0
        MOV      r3,r0
        MOV      r2,r6
        MOV      r1,r4
        STR      r0,[sp,#0]
        MOV      r0,r5
        BL       _ZN6Stream9findUntilEPcjS0_j
        POP      {r3-r7,pc}
        ENDP


        AREA ||i._ZN6Stream4findEPcj||, CODE, READONLY, ALIGN=1

_ZN6Stream4findEPcj PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOVS     r0,#0
        MOV      r3,r0
        MOV      r2,r6
        MOV      r1,r5
        STR      r0,[sp,#0]
        MOV      r0,r4
        BL       _ZN6Stream9findUntilEPcjS0_j
        POP      {r3-r7,pc}
        ENDP


        AREA ||i._ZN6Stream8parseIntE13LookaheadModec||, CODE, READONLY, ALIGN=1

_ZN6Stream8parseIntE13LookaheadModec PROC
        PUSH     {r4-r10,lr}
        MOV      r7,r0
        MOV      r8,r1
        MOV      r5,r2
        MOV      r9,#0
        MOVS     r6,#0
        MOVS     r2,#0
        MOV      r1,r8
        MOV      r0,r7
        BL       _ZN6Stream13peekNextDigitE13LookaheadModeb
        MOV      r4,r0
        CMP      r4,#0
        BGE      |L9.38|
        MOVS     r0,#0
|L9.34|
        POP      {r4-r10,pc}
|L9.38|
        NOP      
|L9.40|
        CMP      r4,r5
        BEQ      |L9.74|
        CMP      r4,#0x2d
        BNE      |L9.54|
        MOV      r9,#1
        B        |L9.74|
|L9.54|
        CMP      r4,#0x30
        BLT      |L9.74|
        CMP      r4,#0x39
        BGT      |L9.74|
        ADD      r0,r6,r6,LSL #2
        ADD      r0,r4,r0,LSL #1
        SUB      r6,r0,#0x30
|L9.74|
        LDR      r0,[r7,#0]
        LDR      r1,[r0,#0xc]
        MOV      r0,r7
        BLX      r1
        MOV      r0,r7
        BL       _ZN6Stream9timedPeekEv
        MOV      r4,r0
        CMP      r4,#0x30
        BLT      |L9.98|
        CMP      r4,#0x39
        BLE      |L9.40|
|L9.98|
        CMP      r4,r5
        BEQ      |L9.40|
        CMP      r9,#0
        BEQ      |L9.110|
        RSBS     r6,r6,#0
|L9.110|
        MOV      r0,r6
        B        |L9.34|
        ENDP


        AREA ||i._ZN6Stream9findMultiEPNS_11MultiTargetEi||, CODE, READONLY, ALIGN=1

_ZN6Stream9findMultiEPNS_11MultiTargetEi PROC
        PUSH     {r4-r8,lr}
        MOV      r7,r0
        MOV      r4,r1
        MOV      r5,r2
        MOV      r1,r4
        B        |L10.32|
|L10.14|
        LDR      r0,[r1,#4]
        CBNZ     r0,|L10.30|
        SUBS     r0,r1,r4
        MOVS     r2,#0xc
        SDIV     r0,r0,r2
|L10.26|
        POP      {r4-r8,pc}
|L10.30|
        ADDS     r1,r1,#0xc
|L10.32|
        ADD      r0,r5,r5,LSL #1
        ADD      r0,r4,r0,LSL #2
        CMP      r0,r1
        BHI      |L10.14|
        B        |L10.266|
|L10.46|
        MOV      r0,r7
        BL       _ZN6Stream9timedReadEv
        MOV      r6,r0
        CMP      r6,#0
        BGE      |L10.64|
        MOV      r0,#0xffffffff
        B        |L10.26|
|L10.64|
        MOV      r1,r4
        B        |L10.252|
|L10.68|
        LDR      r3,[r1,#8]
        LDR      r0,[r1,#0]
        LDRB     r0,[r0,r3]
        CMP      r0,r6
        BNE      |L10.102|
        LDR      r0,[r1,#8]
        ADDS     r0,r0,#1
        STR      r0,[r1,#8]
        LDR      r3,[r1,#4]
        CMP      r0,r3
        BNE      |L10.100|
        SUBS     r0,r1,r4
        MOVS     r3,#0xc
        SDIV     r0,r0,r3
        B        |L10.26|
|L10.100|
        B        |L10.250|
|L10.102|
        LDR      r0,[r1,#8]
        CBNZ     r0,|L10.108|
        B        |L10.250|
|L10.108|
        LDR      r2,[r1,#8]
        NOP      
|L10.112|
        LDR      r12,[r1,#8]
        SUB      r12,r12,#1
        STR      r12,[r1,#8]
        LDR      r12,[r1,#0]
        LDR      r8,[r1,#8]
        LDRB     r12,[r12,r8]
        CMP      r12,r6
        BEQ      |L10.142|
        B        |L10.240|
|L10.142|
        LDR      r12,[r1,#8]
        CMP      r12,#0
        BNE      |L10.166|
        LDR      r12,[r1,#8]
        ADD      r12,r12,#1
        STR      r12,[r1,#8]
        B        |L10.246|
|L10.166|
        LDR      r12,[r1,#8]
        SUB      r3,r2,r12
        MOVS     r0,#0
        B        |L10.206|
|L10.178|
        ADD      r8,r0,r3
        LDR      r12,[r1,#0]
        LDRB     r12,[r12,r8]
        LDR      r8,[r1,#0]
        LDRB     r8,[r8,r0]
        CMP      r12,r8
        BEQ      |L10.204|
        B        |L10.214|
|L10.204|
        ADDS     r0,r0,#1
|L10.206|
        LDR      r12,[r1,#8]
        CMP      r12,r0
        BHI      |L10.178|
|L10.214|
        NOP      
        LDR      r12,[r1,#8]
        CMP      r12,r0
        BNE      |L10.238|
        LDR      r12,[r1,#8]
        ADD      r12,r12,#1
        STR      r12,[r1,#8]
        B        |L10.246|
|L10.238|
        NOP      
|L10.240|
        LDR      r0,[r1,#8]
        CMP      r0,#0
        BNE      |L10.112|
|L10.246|
        NOP      
        NOP      
|L10.250|
        ADDS     r1,r1,#0xc
|L10.252|
        ADD      r0,r5,r5,LSL #1
        ADD      r0,r4,r0,LSL #2
        CMP      r0,r1
        BHI      |L10.68|
        NOP      
|L10.266|
        B        |L10.46|
        ENDP


        AREA ||i._ZN6Stream9findUntilEPcS0_||, CODE, READONLY, ALIGN=1

_ZN6Stream9findUntilEPcS0_ PROC
        PUSH     {r3-r9,lr}
        MOV      r6,r0
        MOV      r5,r1
        MOV      r4,r2
        MOV      r0,r4
        BL       strlen
        MOV      r7,r0
        MOV      r0,r5
        BL       strlen
        MOV      r8,r0
        MOV      r3,r4
        MOV      r2,r8
        MOV      r1,r5
        MOV      r0,r6
        STR      r7,[sp,#0]
        BL       _ZN6Stream9findUntilEPcjS0_j
        POP      {r3-r9,pc}
        ENDP


        AREA ||i._ZN6Stream9findUntilEPcjS0_j||, CODE, READONLY, ALIGN=1

_ZN6Stream9findUntilEPcjS0_j PROC
        PUSH     {r4-r8,lr}
        SUB      sp,sp,#0x18
        MOV      r7,r0
        MOV      r4,r1
        MOV      r5,r2
        MOV      r6,r3
        LDR      r8,[sp,#0x30]
        CBNZ     r6,|L12.56|
        MOVS     r0,#0
        STR      r0,[sp,#0xc]
        STR      r0,[sp,#0x10]
        STR      r0,[sp,#0x14]
        STR      r4,[sp,#0xc]
        STR      r5,[sp,#0x10]
        MOVS     r2,#1
        ADD      r1,sp,#0xc
        MOV      r0,r7
        BL       _ZN6Stream9findMultiEPNS_11MultiTargetEi
        CBNZ     r0,|L12.52|
        MOVS     r0,#1
|L12.46|
        ADD      sp,sp,#0x18
        POP      {r4-r8,pc}
|L12.52|
        MOVS     r0,#0
        B        |L12.46|
|L12.56|
        MOVS     r1,#0x18
        MOV      r0,sp
        BL       __aeabi_memclr4
        STR      r4,[sp,#0]
        STR      r5,[sp,#4]
        STR      r6,[sp,#0xc]
        STR      r8,[sp,#0x10]
        MOVS     r2,#2
        MOV      r1,sp
        MOV      r0,r7
        BL       _ZN6Stream9findMultiEPNS_11MultiTargetEi
        CBNZ     r0,|L12.90|
        MOVS     r0,#1
        B        |L12.46|
|L12.90|
        MOVS     r0,#0
        B        |L12.46|
        ENDP


        AREA ||i._ZN6Stream9readBytesEPcj||, CODE, READONLY, ALIGN=1

_ZN6Stream9readBytesEPcj PROC
        PUSH     {r4-r8,lr}
        MOV      r8,r0
        MOV      r4,r1
        MOV      r6,r2
        MOVS     r5,#0
        B        |L13.36|
|L13.14|
        MOV      r0,r8
        BL       _ZN6Stream9timedReadEv
        MOV      r7,r0
        CMP      r7,#0
        BGE      |L13.28|
        B        |L13.40|
|L13.28|
        STRB     r7,[r4],#1
        ADDS     r5,r5,#1
        NOP      
|L13.36|
        CMP      r5,r6
        BCC      |L13.14|
|L13.40|
        NOP      
        MOV      r0,r5
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN6Stream9timedPeekEv||, CODE, READONLY, ALIGN=1

_ZN6Stream9timedPeekEv PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        BL       millis
        STR      r0,[r4,#0xc]
        NOP      
|L14.12|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x10]
        MOV      r0,r4
        BLX      r1
        MOV      r5,r0
        CMP      r5,#0
        BLT      |L14.30|
        MOV      r0,r5
|L14.28|
        POP      {r4-r6,pc}
|L14.30|
        BL       millis
        LDR      r1,[r4,#0xc]
        SUBS     r0,r0,r1
        LDR      r1,[r4,#8]
        CMP      r0,r1
        BCC      |L14.12|
        MOV      r0,#0xffffffff
        B        |L14.28|
        ENDP


        AREA ||i._ZN6Stream9timedReadEv||, CODE, READONLY, ALIGN=1

_ZN6Stream9timedReadEv PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        BL       millis
        STR      r0,[r4,#0xc]
        NOP      
|L15.12|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0xc]
        MOV      r0,r4
        BLX      r1
        MOV      r5,r0
        CMP      r5,#0
        BLT      |L15.30|
        MOV      r0,r5
|L15.28|
        POP      {r4-r6,pc}
|L15.30|
        BL       millis
        LDR      r1,[r4,#0xc]
        SUBS     r0,r0,r1
        LDR      r1,[r4,#8]
        CMP      r0,r1
        BCC      |L15.12|
        MOV      r0,#0xffffffff
        B        |L15.28|
        ENDP


        AREA ||.ARM.exidx||, LINKORDER=||i.NOPS_FOR_USEC||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||i.NOPS_FOR_USEC||
        DCD      0x00000001

        AREA ||area_number.17||, LINKORDER=||i._ZN6Stream9timedReadEv||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.17||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9timedReadEv||
        DCD      0x00000001

        AREA ||area_number.18||, LINKORDER=||i._ZN6Stream9timedPeekEv||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.18||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9timedPeekEv||
        DCD      0x00000001

        AREA ||area_number.19||, LINKORDER=||i._ZN6Stream13peekNextDigitE13LookaheadModeb||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.19||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream13peekNextDigitE13LookaheadModeb||
        DCD      0x00000001

        AREA ||area_number.20||, LINKORDER=||i._ZN6Stream10setTimeoutEm||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.20||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream10setTimeoutEm||
        DCD      0x00000001

        AREA ||area_number.21||, LINKORDER=||i._ZN6Stream9findMultiEPNS_11MultiTargetEi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.21||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9findMultiEPNS_11MultiTargetEi||
        DCD      0x00000001

        AREA ||area_number.22||, LINKORDER=||i._ZN6Stream9findUntilEPcjS0_j||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.22||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9findUntilEPcjS0_j||
        DCD      0x00000001

        AREA ||area_number.23||, LINKORDER=||i._ZN6Stream4findEPc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.23||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream4findEPc||
        DCD      0x00000001

        AREA ||area_number.24||, LINKORDER=||i._ZN6Stream4findEPcj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.24||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream4findEPcj||
        DCD      0x00000001

        AREA ||area_number.25||, LINKORDER=||i._ZN6Stream9findUntilEPcS0_||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.25||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9findUntilEPcS0_||
        DCD      0x00000001

        AREA ||area_number.26||, LINKORDER=||i._ZN6Stream8parseIntE13LookaheadModec||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.26||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream8parseIntE13LookaheadModec||
        DCD      0x00000001

        AREA ||area_number.27||, LINKORDER=||i._ZN6Stream10parseFloatE13LookaheadModec||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.27||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream10parseFloatE13LookaheadModec||
        DCD      0x00000001

        AREA ||area_number.28||, LINKORDER=||i._ZN6Stream9readBytesEPcj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.28||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream9readBytesEPcj||
        DCD      0x00000001

        AREA ||area_number.29||, LINKORDER=||i._ZN6Stream14readBytesUntilEcPcj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.29||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream14readBytesUntilEcPcj||
        DCD      0x00000001

        AREA ||area_number.30||, LINKORDER=||i._ZN6Stream10readStringEv||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.30||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream10readStringEv||
        DCD      0x00000001

        AREA ||area_number.31||, LINKORDER=||i._ZN6Stream15readStringUntilEc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.31||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6Stream15readStringUntilEc||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN6Stream10parseFloatE13LookaheadModec||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN6Stream10parseFloatE13LookaheadModec||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI6Stream
        DCD      0x00000001
        DCD      0x00000008
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN6Stream13peekNextDigitE13LookaheadModeb||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN6Stream13peekNextDigitE13LookaheadModeb||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI6Stream
        DCD      0x00000001
        DCD      0x00000008
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN6Stream8parseIntE13LookaheadModec||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN6Stream8parseIntE13LookaheadModec||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI6Stream
        DCD      0x00000001
        DCD      0x00000008
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN6Stream9timedPeekEv||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN6Stream9timedPeekEv||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI6Stream
        DCD      0x00000001
        DCD      0x00000010
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN6Stream9timedReadEv||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN6Stream9timedReadEv||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI6Stream
        DCD      0x00000001
        DCD      0x00000008
        DCD      0x00000000
        DCD      0x00000000

        AREA ||i._ZN6StringpLEc||, COMGROUP=_ZN6StringpLEc, CODE, READONLY, ALIGN=1

_ZN6StringpLEc PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN6String6concatEc
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||area_number.108||, COMGROUP=_ZN6StringpLEc, LINKORDER=||i._ZN6StringpLEc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.108||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN6StringpLEc||
        DCD      0x00000001

;*** Start embedded assembler ***

#line 1 "cores\\Stream.cpp"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___10_Stream_cpp_dbd866df___Z7__REV16j|
#line 447 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.1\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___10_Stream_cpp_dbd866df___Z7__REV16j| PROC
#line 448

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___10_Stream_cpp_dbd866df___Z7__REVSHi|
#line 462
|__asm___10_Stream_cpp_dbd866df___Z7__REVSHi| PROC
#line 463

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___10_Stream_cpp_dbd866df___Z5__RRXj|
#line 649
|__asm___10_Stream_cpp_dbd866df___Z5__RRXj| PROC
#line 650

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT NOPS_FOR_USEC [CODE]
        EXPORT _ZN6Stream10parseFloatE13LookaheadModec [CODE]
        EXPORT _ZN6Stream10readStringEv [CODE]
        EXPORT _ZN6Stream10setTimeoutEm [CODE]
        EXPORT _ZN6Stream13peekNextDigitE13LookaheadModeb [CODE]
        EXPORT _ZN6Stream14readBytesUntilEcPcj [CODE]
        EXPORT _ZN6Stream15readStringUntilEc [CODE]
        EXPORT _ZN6Stream4findEPc [CODE]
        EXPORT _ZN6Stream4findEPcj [CODE]
        EXPORT _ZN6Stream8parseIntE13LookaheadModec [CODE]
        EXPORT _ZN6Stream9findMultiEPNS_11MultiTargetEi [CODE]
        EXPORT _ZN6Stream9findUntilEPcS0_ [CODE]
        EXPORT _ZN6Stream9findUntilEPcjS0_j [CODE]
        EXPORT _ZN6Stream9readBytesEPcj [CODE]
        EXPORT _ZN6Stream9timedPeekEv [CODE]
        EXPORT _ZN6Stream9timedReadEv [CODE]
        EXPORT _ZN6StringpLEc [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]
        IMPORT millis [CODE]
        IMPORT __aeabi_memclr4 [CODE]
        IMPORT strlen [CODE]
        IMPORT __aeabi_f2d [CODE]
        IMPORT __aeabi_dmul [CODE]
        IMPORT __aeabi_d2f [CODE]
        IMPORT _ZN6StringC1EPKc [CODE]
        IMPORT _ZN6String6concatEc [CODE]
        IMPORT _ZTI6Stream [DATA,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
