; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\objects\dtostrf.s --depend=.\objects\dtostrf.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\dtostrf.crf cores\dtostrf.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.dtostrf||, CODE, READONLY, ALIGN=2

        REQUIRE _printf_percent
        REQUIRE _printf_d
        REQUIRE _printf_int_dec
        REQUIRE _printf_pre_padding
        REQUIRE _printf_sizespec
        REQUIRE _printf_flags
        REQUIRE _printf_widthprec
        REQUIRE _printf_f
        REQUIRE _printf_e
        REQUIRE _printf_g
        REQUIRE _printf_a
        REQUIRE _printf_fp_hex
        REQUIRE _printf_fp_dec
dtostrf PROC
        PUSH     {r4-r6,lr}
        VPUSH    {d8-d9}
        SUB      sp,sp,#0x18
        VMOV.F32 s16,s0
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r3,r5
        MOV      r2,r4
        ADR      r1,|L0.64|
        ADD      r0,sp,#4
        BL       __2sprintf
        VMOV     r0,s16
        BL       __aeabi_f2d
        VMOV     d9,r0,r1
        VMOV     r2,r3,d9
        ADD      r1,sp,#4
        MOV      r0,r6
        BL       __2sprintf
        MOV      r0,r6
        ADD      sp,sp,#0x18
        VPOP     {d8-d9}
        POP      {r4-r6,pc}
        ENDP

|L0.64|
        DCB      "%%%d.%df",0
        DCB      0
        DCB      0
        DCB      0

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT dtostrf [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT _printf_percent [CODE]
        IMPORT _printf_d [CODE]
        IMPORT _printf_int_dec [CODE]
        IMPORT __2sprintf [CODE]
        IMPORT __aeabi_f2d [CODE]
        IMPORT _printf_pre_padding [CODE]
        IMPORT _printf_sizespec [CODE]
        IMPORT _printf_flags [CODE]
        IMPORT _printf_widthprec [CODE]
        IMPORT _printf_f [CODE]
        IMPORT _printf_e [CODE]
        IMPORT _printf_g [CODE]
        IMPORT _printf_a [CODE]
        IMPORT _printf_fp_hex [CODE]
        IMPORT _printf_fp_dec [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
