; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--cpp --split_sections --debug -c -S -o.\objects\ipaddress.s --depend=.\objects\ipaddress.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\ipaddress.crf cores\IPAddress.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.NOPS_FOR_USEC||, CODE, READONLY, ALIGN=1

NOPS_FOR_USEC PROC
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        BX       lr
        ENDP


        AREA ||i._ZN9IPAddress10fromStringEPKc||, CODE, READONLY, ALIGN=1

_ZN9IPAddress10fromStringEPKc PROC
        PUSH     {r4-r7,lr}
        MOV      r4,r0
        MOVS     r2,#0
        MOVS     r5,#0
        B        |L1.76|
|L1.10|
        LDRB     r3,[r1],#1
        CMP      r3,#0x30
        BLT      |L1.44|
        CMP      r3,#0x39
        BGT      |L1.44|
        SUB      r0,r3,#0x30
        ADD      r6,r2,r2,LSL #2
        ADD      r0,r0,r6,LSL #1
        UXTH     r2,r0
        CMP      r2,#0xff
        BLE      |L1.74|
        MOVS     r0,#0
|L1.42|
        POP      {r4-r7,pc}
|L1.44|
        CMP      r3,#0x2e
        BNE      |L1.70|
        CMP      r5,#3
        BNE      |L1.56|
        MOVS     r0,#0
        B        |L1.42|
|L1.56|
        MOV      r0,r5
        ADDS     r6,r5,#1
        UXTB     r5,r6
        ADDS     r6,r4,#4
        STRB     r2,[r6,r0]
        MOVS     r2,#0
        B        |L1.74|
|L1.70|
        MOVS     r0,#0
        B        |L1.42|
|L1.74|
        NOP      
|L1.76|
        LDRB     r0,[r1,#0]
        CMP      r0,#0
        BNE      |L1.10|
        CMP      r5,#3
        BEQ      |L1.88|
        B        |L1.42|
|L1.88|
        STRB     r2,[r4,#7]
        MOVS     r0,#1
        B        |L1.42|
        ENDP


        AREA ||i._ZN9IPAddressC1EPKh||, CODE, READONLY, ALIGN=2

_ZN9IPAddressC2EPKh                  ; Alternate entry point
_ZN9IPAddressC1EPKh PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r0,r4
        BL       _ZN9PrintableC2Ev
        MOV      r4,r0
        LDR      r0,|L2.28|
        STR      r0,[r4,#0]
        LDR      r0,[r5,#0]
        STR      r0,[r4,#4]
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L2.28|
        DCD      _ZTV9IPAddress+0x8

        AREA ||i._ZN9IPAddressC1Ehhhh||, CODE, READONLY, ALIGN=2

_ZN9IPAddressC2Ehhhh                  ; Alternate entry point
_ZN9IPAddressC1Ehhhh PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r7,r3
        LDR      r8,[sp,#0x18]
        MOV      r0,r4
        BL       _ZN9PrintableC2Ev
        MOV      r4,r0
        LDR      r0,|L3.44|
        STR      r0,[r4,#0]
        STRB     r5,[r4,#4]
        STRB     r6,[r4,#5]
        STRB     r7,[r4,#6]
        STRB     r8,[r4,#7]
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP

|L3.44|
        DCD      _ZTV9IPAddress+0x8

        AREA ||i._ZN9IPAddressC1Ej||, CODE, READONLY, ALIGN=2

_ZN9IPAddressC2Ej                  ; Alternate entry point
_ZN9IPAddressC1Ej PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r0,r4
        BL       _ZN9PrintableC2Ev
        MOV      r4,r0
        LDR      r0,|L4.24|
        STR      r0,[r4,#0]
        STR      r5,[r4,#4]
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP

|L4.24|
        DCD      _ZTV9IPAddress+0x8

        AREA ||i._ZN9IPAddressC1Ev||, CODE, READONLY, ALIGN=2

_ZN9IPAddressC2Ev                  ; Alternate entry point
_ZN9IPAddressC1Ev PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOV      r0,r4
        BL       _ZN9PrintableC2Ev
        MOV      r4,r0
        LDR      r0,|L5.24|
        STR      r0,[r4,#0]
        MOVS     r0,#0
        STR      r0,[r4,#4]
        MOV      r0,r4
        POP      {r4,pc}
        ENDP

|L5.24|
        DCD      _ZTV9IPAddress+0x8

        AREA ||i._ZN9IPAddressaSEPKh||, CODE, READONLY, ALIGN=1

_ZN9IPAddressaSEPKh PROC
        LDR      r2,[r1,#0]
        STR      r2,[r0,#4]
        BX       lr
        ENDP


        AREA ||i._ZN9IPAddressaSEj||, CODE, READONLY, ALIGN=1

_ZN9IPAddressaSEj PROC
        STR      r1,[r0,#4]
        BX       lr
        ENDP


        AREA ||i._ZNK9IPAddress7printToER5Print||, CODE, READONLY, ALIGN=1

_ZNK9IPAddress7printToER5Print PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r7,r1
        MOVS     r4,#0
        MOVS     r6,#0
        B        |L8.40|
|L8.14|
        ADDS     r0,r5,#4
        LDRB     r1,[r0,r6]
        MOVS     r2,#0xa
        MOV      r0,r7
        BL       _ZN5Print5printEhi
        ADD      r4,r4,r0
        MOVS     r1,#0x2e
        MOV      r0,r7
        BL       _ZN5Print5printEc
        ADD      r4,r4,r0
        ADDS     r6,r6,#1
|L8.40|
        CMP      r6,#3
        BLT      |L8.14|
        LDRB     r1,[r5,#7]
        MOVS     r2,#0xa
        MOV      r0,r7
        BL       _ZN5Print5printEhi
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZNK9IPAddresseqEPKh||, CODE, READONLY, ALIGN=1

_ZNK9IPAddresseqEPKh PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOVS     r2,#4
        ADDS     r1,r5,#4
        MOV      r0,r4
        BL       memcmp
        CBNZ     r0,|L9.22|
        MOVS     r0,#1
|L9.20|
        POP      {r4-r6,pc}
|L9.22|
        MOVS     r0,#0
        B        |L9.20|
        ENDP


        AREA ||i.__sti___13_IPAddress_cpp_dbd866df||, CODE, READONLY, ALIGN=2

__sti___13_IPAddress_cpp_dbd866df PROC
        PUSH     {r3,lr}
        MOVS     r0,#0
        MOV      r3,r0
        MOV      r2,r0
        MOV      r1,r0
        STR      r0,[sp,#0]
        LDR      r0,|L10.20|
        BL       _ZN9IPAddressC1Ehhhh
        POP      {r3,pc}
        ENDP

|L10.20|
        DCD      INADDR_NONE

        AREA ||.ARM.exidx||, LINKORDER=||i.NOPS_FOR_USEC||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||i.NOPS_FOR_USEC||
        DCD      0x00000001

        AREA ||area_number.12||, LINKORDER=||i._ZN9IPAddressC1Ev||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.12||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressC1Ev||
        DCD      0x00000001

        AREA ||area_number.13||, LINKORDER=||i._ZN9IPAddressC1Ehhhh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.13||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressC1Ehhhh||
        DCD      0x00000001

        AREA ||area_number.14||, LINKORDER=||i._ZN9IPAddressC1Ej||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.14||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressC1Ej||
        DCD      0x00000001

        AREA ||area_number.15||, LINKORDER=||i._ZN9IPAddressC1EPKh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.15||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressC1EPKh||
        DCD      0x00000001

        AREA ||area_number.16||, LINKORDER=||i._ZN9IPAddress10fromStringEPKc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.16||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddress10fromStringEPKc||
        DCD      0x00000001

        AREA ||area_number.17||, LINKORDER=||i._ZNK9IPAddresseqEPKh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.17||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZNK9IPAddresseqEPKh||
        DCD      0x00000001

        AREA ||area_number.18||, LINKORDER=||i._ZN9IPAddressaSEPKh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.18||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressaSEPKh||
        DCD      0x00000001

        AREA ||area_number.19||, LINKORDER=||i._ZN9IPAddressaSEj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.19||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9IPAddressaSEj||
        DCD      0x00000001

        AREA ||area_number.20||, LINKORDER=||i._ZNK9IPAddress7printToER5Print||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.20||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZNK9IPAddress7printToER5Print||
        DCD      0x00000001

        AREA ||area_number.21||, LINKORDER=||i.__sti___13_IPAddress_cpp_dbd866df||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.21||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i.__sti___13_IPAddress_cpp_dbd866df||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

INADDR_NONE
        %        8

        AREA ||.init_array||, DATA, READONLY, INIT_ARRAY, ALIGN=2

        DCD      0x00000000
        RELOC 38, __sti___13_IPAddress_cpp_dbd866df

        AREA ||.arm_vfe_vtableinfo_ZTV9IPAddress||, COMGROUP=_ZTV9IPAddress, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||$weak$_ZTV9IPAddress||
        DCD      0x00000003
        DCD      0x00000002
        DCD      ||$weak$_ZTI9IPAddress||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000
        DCD      ||$weak$_ZTI9Printable||
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI9IPAddress||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000

        AREA ||.constdata__ZTV9IPAddress||, COMGROUP=_ZTV9IPAddress, DATA, READONLY, ALIGN=2

_ZTV9IPAddress
        DCD      0x00000000
        DCD      _ZTI9IPAddress
        DCD      _ZNK9IPAddress7printToER5Print

        AREA ||i._ZN9PrintableC2Ev||, COMGROUP=_ZN9PrintableC2Ev, CODE, READONLY, ALIGN=2

_ZN9PrintableC2Ev PROC
        LDR      r1,|L74.8|
        STR      r1,[r0,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L74.8|
        DCD      _ZTV9Printable+0x8

        AREA ||area_number.75||, COMGROUP=_ZN9PrintableC2Ev, LINKORDER=||i._ZN9PrintableC2Ev||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.75||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN9PrintableC2Ev||
        DCD      0x00000001

        AREA ||.arm_vfe_vtableinfo_ZTV9Printable||, COMGROUP=_ZTV9Printable, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||$weak$_ZTV9Printable||
        DCD      0x00000003
        DCD      0x00000001
        DCD      ||$weak$_ZTI9Printable||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000

        AREA ||.constdata__ZTV9Printable||, COMGROUP=_ZTV9Printable, DATA, READONLY, ALIGN=2

_ZTV9Printable
        DCD      0x00000000
        DCD      _ZTI9Printable
        DCD      __cxa_pure_virtual

        AREA ||.constdata__ZTI9IPAddress||, COMGROUP=_ZTI9IPAddress, DATA, READONLY, ALIGN=2

_ZTI9IPAddress
        DCD      _ZTVN10__cxxabiv120__si_class_type_infoE+0x8
        DCD      _ZTS9IPAddress
        DCD      _ZTI9Printable

        AREA ||.constdata__ZTI9Printable||, COMGROUP=_ZTI9Printable, DATA, READONLY, ALIGN=2

_ZTI9Printable
        DCD      _ZTVN10__cxxabiv117__class_type_infoE+0x8
        DCD      _ZTS9Printable

        AREA ||.constdata__ZTS9IPAddress||, COMGROUP=_ZTS9IPAddress, DATA, READONLY, ALIGN=0

_ZTS9IPAddress
        DCB      0x39,0x49,0x50,0x41
        DCB      0x64,0x64,0x72,0x65
        DCB      0x73,0x73,0x00

        AREA ||.constdata__ZTS9Printable||, COMGROUP=_ZTS9Printable, DATA, READONLY, ALIGN=0

_ZTS9Printable
        DCB      0x39,0x50,0x72,0x69
        DCB      0x6e,0x74,0x61,0x62
        DCB      0x6c,0x65,0x00

;*** Start embedded assembler ***

#line 1 "cores\\IPAddress.cpp"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___13_IPAddress_cpp_dbd866df___Z7__REV16j|
#line 447 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.1\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___13_IPAddress_cpp_dbd866df___Z7__REV16j| PROC
#line 448

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___13_IPAddress_cpp_dbd866df___Z7__REVSHi|
#line 462
|__asm___13_IPAddress_cpp_dbd866df___Z7__REVSHi| PROC
#line 463

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___13_IPAddress_cpp_dbd866df___Z5__RRXj|
#line 649
|__asm___13_IPAddress_cpp_dbd866df___Z5__RRXj| PROC
#line 650

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT NOPS_FOR_USEC [CODE]
        EXPORT _ZN9IPAddress10fromStringEPKc [CODE]
        EXPORT _ZN9IPAddressC2EPKh [CODE]
        EXPORT _ZN9IPAddressC1EPKh [CODE]
        EXPORT _ZN9IPAddressC2Ehhhh [CODE]
        EXPORT _ZN9IPAddressC1Ehhhh [CODE]
        EXPORT _ZN9IPAddressC2Ej [CODE]
        EXPORT _ZN9IPAddressC1Ej [CODE]
        EXPORT _ZN9IPAddressC2Ev [CODE]
        EXPORT _ZN9IPAddressC1Ev [CODE]
        EXPORT _ZN9IPAddressaSEPKh [CODE]
        EXPORT _ZN9IPAddressaSEj [CODE]
        EXPORT _ZNK9IPAddress7printToER5Print [CODE]
        EXPORT _ZNK9IPAddresseqEPKh [CODE]
        EXPORT _ZTV9IPAddress [DATA,SIZE=12]
        EXPORT _ZN9PrintableC2Ev [CODE]
        EXPORT _ZTV9Printable [DATA,SIZE=12]
        EXPORT _ZTI9IPAddress [DATA,SIZE=12]
        EXPORT _ZTI9Printable [DATA,SIZE=8]
        EXPORT _ZTS9IPAddress [DATA,SIZE=11]
        EXPORT _ZTS9Printable [DATA,SIZE=11]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]
        IMPORT ||$weak$_ZTV9IPAddress|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTV9IPAddress||, _ZTV9IPAddress
        IMPORT ||$weak$_ZTI9IPAddress|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTI9IPAddress||, _ZTI9IPAddress
        IMPORT ||$weak$_ZTI9Printable|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTI9Printable||, _ZTI9Printable
        IMPORT memcmp [CODE]
        IMPORT _ZN5Print5printEhi [CODE]
        IMPORT _ZN5Print5printEc [CODE]
        IMPORT ||$weak$_ZTV9Printable|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTV9Printable||, _ZTV9Printable
        IMPORT __cxa_pure_virtual [CODE]
        IMPORT _ZTVN10__cxxabiv120__si_class_type_infoE [DATA]
        IMPORT _ZTVN10__cxxabiv117__class_type_infoE [DATA]

        KEEP __sti___13_IPAddress_cpp_dbd866df
        KEEP INADDR_NONE

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
