; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--cpp --split_sections --debug -c -S -o.\objects\print.s --depend=.\objects\print.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\print.crf cores\Print.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.NOPS_FOR_USEC||, CODE, READONLY, ALIGN=1

NOPS_FOR_USEC PROC
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        BX       lr
        ENDP


        AREA ||i._ZN5Print10printFloatEdh||, CODE, READONLY, ALIGN=2

_ZN5Print10printFloatEdh PROC
        PUSH     {r4-r8,lr}
        VPUSH    {d8-d11}
        SUB      sp,sp,#8
        MOV      r7,r0
        VMOV.F32 s16,s0
        VMOV.F32 s17,s1
        MOV      r5,r1
        MOVS     r4,#0
        VSTR     d8,[sp,#0]
        LDRD     r2,r1,[sp,#0]
        CBZ      r2,|L1.38|
        MOVS     r2,#1
        B        |L1.40|
|L1.38|
        MOVS     r2,#0
|L1.40|
        ORR      r0,r1,r2
        BIC      r1,r0,#0x80000000
        LDR      r2,|L1.400|
        SUBS     r1,r2,r1
        LSRS     r1,r1,#31
        CBZ      r1,|L1.74|
        ADR      r1,|L1.404|
        MOV      r0,r7
        BL       _ZN5Print5printEPKc
|L1.64|
        ADD      sp,sp,#8
        VPOP     {d8-d11}
        POP      {r4-r8,pc}
|L1.74|
        VSTR     d8,[sp,#0]
        LDR      r1,|L1.408|
        LDR      r0,[sp,#4]
        CMP      r1,r0,LSL #1
        BNE      |L1.96|
        LDR      r0,[sp,#0]
        CBNZ     r0,|L1.96|
        MOVS     r0,#1
        B        |L1.98|
|L1.96|
        MOVS     r0,#0
|L1.98|
        CBZ      r0,|L1.110|
        ADR      r1,|L1.412|
        MOV      r0,r7
        BL       _ZN5Print5printEPKc
        B        |L1.64|
|L1.110|
        VLDR     d0,|L1.416|
        VMOV     r2,r3,d0
        VMOV     r0,r1,d8
        BL       __aeabi_cdrcmple
        BCS      |L1.138|
        ADR      r1,|L1.424|
        MOV      r0,r7
        BL       _ZN5Print5printEPKc
        B        |L1.64|
|L1.138|
        VLDR     d0,|L1.428|
        VMOV     r2,r3,d0
        VMOV     r0,r1,d8
        BL       __aeabi_cdcmple
        BCS      |L1.166|
        ADR      r1,|L1.424|
        MOV      r0,r7
        BL       _ZN5Print5printEPKc
        B        |L1.64|
|L1.166|
        VLDR     d0,|L1.436|
        VMOV     r2,r3,d0
        VMOV     r0,r1,d8
        BL       __aeabi_cdcmple
        BCS      |L1.206|
        MOVS     r1,#0x2d
        MOV      r0,r7
        BL       _ZN5Print5printEc
        ADD      r4,r4,r0
        VMOV     r0,r1,d8
        BL       __aeabi_dneg
        VMOV     d8,r0,r1
|L1.206|
        VLDR     d9,|L1.444|
        MOVS     r6,#0
        B        |L1.238|
|L1.214|
        VLDR     d0,|L1.452|
        VMOV     r2,r3,d0
        VMOV     r0,r1,d9
        BL       __aeabi_ddiv
        VMOV     d9,r0,r1
        ADDS     r0,r6,#1
        UXTB     r6,r0
|L1.238|
        CMP      r6,r5
        BLT      |L1.214|
        VMOV     r2,r3,d9
        VMOV     r0,r1,d8
        BL       __aeabi_dadd
        VMOV     d8,r0,r1
        VMOV     r0,r1,d8
        BL       __aeabi_d2uiz
        MOV      r8,r0
        MOV      r0,r8
        BL       __aeabi_ui2d
        VMOV     d11,r0,r1
        VMOV     r2,r3,d8
        BL       __aeabi_drsub
        VMOV     d10,r0,r1
        MOVS     r2,#0xa
        MOV      r1,r8
        MOV      r0,r7
        BL       _ZN5Print5printEmi
        ADD      r4,r4,r0
        CMP      r5,#0
        BLE      |L1.316|
        ADR      r1,|L1.460|
        MOV      r0,r7
        BL       _ZN5Print5printEPKc
        ADD      r4,r4,r0
|L1.316|
        B        |L1.384|
|L1.318|
        VLDR     d0,|L1.452|
        VMOV     r2,r3,d0
        VMOV     r0,r1,d10
        BL       __aeabi_dmul
        VMOV     d10,r0,r1
        VMOV     r0,r1,d10
        BL       __aeabi_d2uiz
        MOV      r6,r0
        MOVS     r2,#0xa
        MOV      r1,r6
        MOV      r0,r7
        BL       _ZN5Print5printEji
        ADD      r4,r4,r0
        MOV      r0,r6
        BL       __aeabi_ui2d
        VMOV     d11,r0,r1
        VMOV     r2,r3,d10
        BL       __aeabi_drsub
        VMOV     d10,r0,r1
        NOP      
|L1.384|
        SUBS     r0,r5,#0
        SUB      r1,r5,#1
        UXTB     r5,r1
        BGT      |L1.318|
        MOV      r0,r4
        B        |L1.64|
        ENDP

        DCW      0x0000
|L1.400|
        DCD      0x7ff00000
|L1.404|
        DCB      "nan",0
|L1.408|
        DCD      0xffe00000
|L1.412|
        DCB      "inf",0
|L1.416|
        DCFD     0x41efffffe0000000 ; 4294967040
|L1.424|
        DCB      "ovf",0
|L1.428|
        DCFD     0xc1efffffe0000000 ; -4294967040
|L1.436|
        DCFD     0x0000000000000000 ; 0
|L1.444|
        DCFD     0x3fe0000000000000 ; 0.5
|L1.452|
        DCFD     0x4024000000000000 ; 10
|L1.460|
        DCB      ".",0
        DCB      0
        DCB      0

        AREA ||i._ZN5Print11printNumberEmh||, CODE, READONLY, ALIGN=1

_ZN5Print11printNumberEmh PROC
        PUSH     {r4-r7,lr}
        SUB      sp,sp,#0x24
        MOV      r7,r0
        MOV      r4,r1
        MOV      r5,r2
        ADD      r6,sp,#0x20
        MOVS     r0,#0
        STRB     r0,[r6,#0]
        CMP      r5,#2
        BGE      |L2.22|
        MOVS     r5,#0xa
|L2.22|
        NOP      
|L2.24|
        UDIV     r1,r4,r5
        MLS      r1,r5,r1,r4
        UXTB     r0,r1
        UDIV     r4,r4,r5
        CMP      r0,#0xa
        BGE      |L2.48|
        ADD      r1,r0,#0x30
        B        |L2.52|
|L2.48|
        ADD      r1,r0,#0x37
|L2.52|
        UXTB     r2,r1
        SUBS     r1,r6,#1
        MOV      r6,r1
        STRB     r2,[r1,#0]
        CMP      r4,#0
        BNE      |L2.24|
        MOV      r1,r6
        MOV      r0,r7
        BL       _ZN5Print5writeEPKc
        ADD      sp,sp,#0x24
        POP      {r4-r7,pc}
        ENDP


        AREA ||i._ZN5Print5printEPK19__FlashStringHelper||, CODE, READONLY, ALIGN=1

_ZN5Print5printEPK19__FlashStringHelper PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN5Print5printEPKc
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEPKc||, CODE, READONLY, ALIGN=1

_ZN5Print5printEPKc PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN5Print5writeEPKc
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printERK6String||, CODE, READONLY, ALIGN=1

_ZN5Print5printERK6String PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r5,r1
        NOP      
        LDR      r6,[r5,#0]
        NOP      
        LDR      r7,[r5,#8]
        NOP      
        LDR      r0,[r4,#0]
        MOV      r2,r7
        MOV      r1,r6
        LDR      r3,[r0,#4]
        MOV      r0,r4
        BLX      r3
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print5printERK9Printable||, CODE, READONLY, ALIGN=1

_ZN5Print5printERK9Printable PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r4,r1
        LDR      r0,[r4,#0]
        MOV      r1,r5
        LDR      r2,[r0,#0]
        MOV      r0,r4
        BLX      r2
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEc||, CODE, READONLY, ALIGN=1

_ZN5Print5printEc PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        LDR      r0,[r4,#0]
        MOV      r1,r5
        LDR      r2,[r0,#0]
        MOV      r0,r4
        BLX      r2
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEdi||, CODE, READONLY, ALIGN=1

_ZN5Print5printEdi PROC
        PUSH     {r4-r6,lr}
        VPUSH    {d8}
        MOV      r5,r0
        VMOV.F32 s16,s0
        VMOV.F32 s17,s1
        MOV      r4,r1
        UXTB     r1,r4
        VMOV.F32 s0,s16
        VMOV.F32 s1,s17
        MOV      r0,r5
        BL       _ZN5Print10printFloatEdh
        VPOP     {d8}
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEhi||, CODE, READONLY, ALIGN=1

_ZN5Print5printEhi PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r2,r6
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN5Print5printEmi
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEii||, CODE, READONLY, ALIGN=1

_ZN5Print5printEii PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r2,r6
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN5Print5printEli
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEji||, CODE, READONLY, ALIGN=1

_ZN5Print5printEji PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r6,r2
        MOV      r2,r6
        MOV      r1,r5
        MOV      r0,r4
        BL       _ZN5Print5printEmi
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print5printEli||, CODE, READONLY, ALIGN=1

_ZN5Print5printEli PROC
        PUSH     {r4-r8,lr}
        MOV      r6,r0
        MOV      r4,r1
        MOV      r5,r2
        CBNZ     r5,|L12.26|
        UXTB     r1,r4
        LDR      r0,[r6,#0]
        LDR      r2,[r0,#0]
        MOV      r0,r6
        BLX      r2
|L12.22|
        POP      {r4-r8,pc}
|L12.26|
        CMP      r5,#0xa
        BNE      |L12.72|
        CMP      r4,#0
        BGE      |L12.60|
        MOVS     r1,#0x2d
        MOV      r0,r6
        BL       _ZN5Print5printEc
        MOV      r7,r0
        RSBS     r4,r4,#0
        MOVS     r2,#0xa
        MOV      r1,r4
        MOV      r0,r6
        BL       _ZN5Print11printNumberEmh
        ADD      r0,r0,r7
        B        |L12.22|
|L12.60|
        MOVS     r2,#0xa
        MOV      r1,r4
        MOV      r0,r6
        BL       _ZN5Print11printNumberEmh
        B        |L12.22|
|L12.72|
        UXTB     r2,r5
        MOV      r1,r4
        MOV      r0,r6
        BL       _ZN5Print11printNumberEmh
        B        |L12.22|
        ENDP


        AREA ||i._ZN5Print5printEmi||, CODE, READONLY, ALIGN=1

_ZN5Print5printEmi PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r4,r2
        CBNZ     r4,|L13.22|
        UXTB     r1,r6
        LDR      r0,[r5,#0]
        LDR      r2,[r0,#0]
        MOV      r0,r5
        BLX      r2
|L13.20|
        POP      {r4-r6,pc}
|L13.22|
        UXTB     r2,r4
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print11printNumberEmh
        B        |L13.20|
        ENDP


        AREA ||i._ZN5Print5writeEPKhj||, CODE, READONLY, ALIGN=1

_ZN5Print5writeEPKhj PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r4,r1
        MOV      r6,r2
        MOVS     r7,#0
        B        |L14.34|
|L14.14|
        LDRB     r1,[r4],#1
        LDR      r0,[r5,#0]
        LDR      r2,[r0,#0]
        MOV      r0,r5
        BLX      r2
        CBZ      r0,|L14.32|
        ADDS     r7,r7,#1
        B        |L14.34|
|L14.32|
        B        |L14.42|
|L14.34|
        SUBS     r0,r6,#0
        SUB      r6,r6,#1
        BNE      |L14.14|
|L14.42|
        NOP      
        MOV      r0,r7
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEPK19__FlashStringHelper||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEPK19__FlashStringHelper PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEPK19__FlashStringHelper
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEPKc||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEPKc PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEPKc
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnERK6String||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnERK6String PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printERK6String
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnERK9Printable||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnERK9Printable PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printERK9Printable
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEc||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEc PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEc
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEdi||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEdi PROC
        PUSH     {r4-r6,lr}
        VPUSH    {d8}
        MOV      r5,r0
        VMOV.F32 s16,s0
        VMOV.F32 s17,s1
        MOV      r6,r1
        MOV      r1,r6
        VMOV.F32 s0,s16
        VMOV.F32 s1,s17
        MOV      r0,r5
        BL       _ZN5Print5printEdi
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        VPOP     {d8}
        POP      {r4-r6,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEhi||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEhi PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEhi
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEii||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEii PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEii
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEji||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEji PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEji
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEli||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEli PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEli
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEmi||, CODE, READONLY, ALIGN=1

_ZN5Print7printlnEmi PROC
        PUSH     {r4-r8,lr}
        MOV      r5,r0
        MOV      r6,r1
        MOV      r7,r2
        MOV      r2,r7
        MOV      r1,r6
        MOV      r0,r5
        BL       _ZN5Print5printEmi
        MOV      r4,r0
        MOV      r0,r5
        BL       _ZN5Print7printlnEv
        ADD      r4,r4,r0
        MOV      r0,r4
        POP      {r4-r8,pc}
        ENDP


        AREA ||i._ZN5Print7printlnEv||, CODE, READONLY, ALIGN=2

_ZN5Print7printlnEv PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        ADR      r1,|L26.16|
        MOV      r0,r4
        BL       _ZN5Print5writeEPKc
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L26.16|
        DCB      "\r\n",0
        DCB      0

        AREA ||.ARM.exidx||, LINKORDER=||i.NOPS_FOR_USEC||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||i.NOPS_FOR_USEC||
        DCD      0x00000001

        AREA ||area_number.28||, LINKORDER=||i._ZN5Print11printNumberEmh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.28||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print11printNumberEmh||
        DCD      0x00000001

        AREA ||area_number.29||, LINKORDER=||i._ZN5Print5printEmi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.29||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEmi||
        DCD      0x00000001

        AREA ||area_number.30||, LINKORDER=||i._ZN5Print5printEji||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.30||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEji||
        DCD      0x00000001

        AREA ||area_number.31||, LINKORDER=||i._ZN5Print5printEPKc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.31||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEPKc||
        DCD      0x00000001

        AREA ||area_number.32||, LINKORDER=||i._ZN5Print5printEc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.32||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEc||
        DCD      0x00000001

        AREA ||area_number.33||, LINKORDER=||i._ZN5Print10printFloatEdh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.33||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print10printFloatEdh||
        DCD      0x00000001

        AREA ||area_number.34||, LINKORDER=||i._ZN5Print5writeEPKhj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.34||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5writeEPKhj||
        DCD      0x00000001

        AREA ||area_number.35||, LINKORDER=||i._ZN5Print5printEPK19__FlashStringHelper||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.35||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEPK19__FlashStringHelper||
        DCD      0x00000001

        AREA ||area_number.36||, LINKORDER=||i._ZN5Print5printERK6String||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.36||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printERK6String||
        DCD      0x00000001

        AREA ||area_number.37||, LINKORDER=||i._ZN5Print5printEhi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.37||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEhi||
        DCD      0x00000001

        AREA ||area_number.38||, LINKORDER=||i._ZN5Print5printEli||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.38||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEli||
        DCD      0x00000001

        AREA ||area_number.39||, LINKORDER=||i._ZN5Print5printEii||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.39||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEii||
        DCD      0x00000001

        AREA ||area_number.40||, LINKORDER=||i._ZN5Print5printEdi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.40||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printEdi||
        DCD      0x00000001

        AREA ||area_number.41||, LINKORDER=||i._ZN5Print5printERK9Printable||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.41||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5printERK9Printable||
        DCD      0x00000001

        AREA ||area_number.42||, LINKORDER=||i._ZN5Print7printlnEv||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.42||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEv||
        DCD      0x00000001

        AREA ||area_number.43||, LINKORDER=||i._ZN5Print7printlnEPK19__FlashStringHelper||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.43||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEPK19__FlashStringHelper||
        DCD      0x00000001

        AREA ||area_number.44||, LINKORDER=||i._ZN5Print7printlnERK6String||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.44||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnERK6String||
        DCD      0x00000001

        AREA ||area_number.45||, LINKORDER=||i._ZN5Print7printlnEPKc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.45||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEPKc||
        DCD      0x00000001

        AREA ||area_number.46||, LINKORDER=||i._ZN5Print7printlnEc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.46||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEc||
        DCD      0x00000001

        AREA ||area_number.47||, LINKORDER=||i._ZN5Print7printlnEhi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.47||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEhi||
        DCD      0x00000001

        AREA ||area_number.48||, LINKORDER=||i._ZN5Print7printlnEii||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.48||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEii||
        DCD      0x00000001

        AREA ||area_number.49||, LINKORDER=||i._ZN5Print7printlnEji||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.49||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEji||
        DCD      0x00000001

        AREA ||area_number.50||, LINKORDER=||i._ZN5Print7printlnEli||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.50||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEli||
        DCD      0x00000001

        AREA ||area_number.51||, LINKORDER=||i._ZN5Print7printlnEmi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.51||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEmi||
        DCD      0x00000001

        AREA ||area_number.52||, LINKORDER=||i._ZN5Print7printlnEdi||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.52||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnEdi||
        DCD      0x00000001

        AREA ||area_number.53||, LINKORDER=||i._ZN5Print7printlnERK9Printable||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.53||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print7printlnERK9Printable||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5printERK6String||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5printERK6String||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5printERK9Printable||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5printERK9Printable||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      _ZTI9Printable
        DCD      0x00000001
        DCD      0x00000001
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5printEc||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5printEc||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000001
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5printEli||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5printEli||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000001
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5printEmi||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5printEmi||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000001
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5writeEPKhj||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5writeEPKhj||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000001
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.arm_vfe_vtableinfo_ZTV5Print||, COMGROUP=_ZTV5Print, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||$weak$_ZTV5Print||
        DCD      0x00000004
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000

        AREA ||.constdata__ZTV5Print||, COMGROUP=_ZTV5Print, DATA, READONLY, ALIGN=2

_ZTV5Print
        DCD      0x00000000
        DCD      _ZTI5Print
        DCD      __cxa_pure_virtual
        DCD      _ZN5Print5writeEPKhj

        AREA ||i._ZN5Print5writeEPKc||, COMGROUP=_ZN5Print5writeEPKc, CODE, READONLY, ALIGN=1

_ZN5Print5writeEPKc PROC
        PUSH     {r4-r6,lr}
        MOV      r5,r0
        MOV      r4,r1
        CBNZ     r4,|L176.12|
        MOVS     r0,#0
|L176.10|
        POP      {r4-r6,pc}
|L176.12|
        MOV      r0,r4
        BL       strlen
        MOV      r6,r0
        LDR      r0,[r5,#0]
        MOV      r2,r6
        MOV      r1,r4
        LDR      r3,[r0,#4]
        MOV      r0,r5
        BLX      r3
        B        |L176.10|
        ENDP


        AREA ||area_number.177||, COMGROUP=_ZN5Print5writeEPKc, LINKORDER=||i._ZN5Print5writeEPKc||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.177||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._ZN5Print5writeEPKc||
        DCD      0x00000001

        AREA ||.arm_vfe_vcallinfoi._ZN5Print5writeEPKc||, COMGROUP=_ZN5Print5writeEPKc, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      ||i._ZN5Print5writeEPKc||
        DCD      0x00000000
        DCD      0x00000000
        DCD      0x00000001
        DCD      ||$weak$_ZTI5Print||
        DCD      0x00000001
        DCD      0x00000002
        DCD      0x00000000
        DCD      0x00000000

        AREA ||.constdata__ZTI5Print||, COMGROUP=_ZTI5Print, DATA, READONLY, ALIGN=2

_ZTI5Print
        DCD      _ZTVN10__cxxabiv117__class_type_infoE+0x8
        DCD      _ZTS5Print

        AREA ||.constdata__ZTS5Print||, COMGROUP=_ZTS5Print, DATA, READONLY, ALIGN=0

_ZTS5Print
        DCB      0x35,0x50,0x72,0x69
        DCB      0x6e,0x74,0x00

;*** Start embedded assembler ***

#line 1 "cores\\Print.cpp"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___9_Print_cpp_dbd866df___Z7__REV16j|
#line 447 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.1\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___9_Print_cpp_dbd866df___Z7__REV16j| PROC
#line 448

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___9_Print_cpp_dbd866df___Z7__REVSHi|
#line 462
|__asm___9_Print_cpp_dbd866df___Z7__REVSHi| PROC
#line 463

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___9_Print_cpp_dbd866df___Z5__RRXj|
#line 649
|__asm___9_Print_cpp_dbd866df___Z5__RRXj| PROC
#line 650

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT NOPS_FOR_USEC [CODE]
        EXPORT _ZN5Print10printFloatEdh [CODE]
        EXPORT _ZN5Print11printNumberEmh [CODE]
        EXPORT _ZN5Print5printEPK19__FlashStringHelper [CODE]
        EXPORT _ZN5Print5printEPKc [CODE]
        EXPORT _ZN5Print5printERK6String [CODE]
        EXPORT _ZN5Print5printERK9Printable [CODE]
        EXPORT _ZN5Print5printEc [CODE]
        EXPORT _ZN5Print5printEdi [CODE]
        EXPORT _ZN5Print5printEhi [CODE]
        EXPORT _ZN5Print5printEii [CODE]
        EXPORT _ZN5Print5printEji [CODE]
        EXPORT _ZN5Print5printEli [CODE]
        EXPORT _ZN5Print5printEmi [CODE]
        EXPORT _ZN5Print5writeEPKhj [CODE]
        EXPORT _ZN5Print7printlnEPK19__FlashStringHelper [CODE]
        EXPORT _ZN5Print7printlnEPKc [CODE]
        EXPORT _ZN5Print7printlnERK6String [CODE]
        EXPORT _ZN5Print7printlnERK9Printable [CODE]
        EXPORT _ZN5Print7printlnEc [CODE]
        EXPORT _ZN5Print7printlnEdi [CODE]
        EXPORT _ZN5Print7printlnEhi [CODE]
        EXPORT _ZN5Print7printlnEii [CODE]
        EXPORT _ZN5Print7printlnEji [CODE]
        EXPORT _ZN5Print7printlnEli [CODE]
        EXPORT _ZN5Print7printlnEmi [CODE]
        EXPORT _ZN5Print7printlnEv [CODE]
        EXPORT _ZTV5Print [DATA,SIZE=16]
        EXPORT _ZN5Print5writeEPKc [CODE]
        EXPORT _ZTI5Print [DATA,SIZE=8]
        EXPORT _ZTS5Print [DATA,SIZE=7]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]
        IMPORT ||$weak$_ZTV5Print|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTV5Print||, _ZTV5Print
        IMPORT ||$weak$_ZTI5Print|| [DATA,WEAK]
        EXPORTAS ||$weak$_ZTI5Print||, _ZTI5Print
        IMPORT __cxa_pure_virtual [CODE]
        IMPORT strlen [CODE]
        IMPORT __aeabi_cdrcmple [CODE]
        IMPORT __aeabi_cdcmple [CODE]
        IMPORT __aeabi_dneg [CODE]
        IMPORT __aeabi_ddiv [CODE]
        IMPORT __aeabi_dadd [CODE]
        IMPORT __aeabi_d2uiz [CODE]
        IMPORT __aeabi_ui2d [CODE]
        IMPORT __aeabi_drsub [CODE]
        IMPORT __aeabi_dmul [CODE]
        IMPORT _ZTVN10__cxxabiv117__class_type_infoE [DATA]
        IMPORT _ZTI9Printable [DATA,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
