; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--cpp --split_sections --debug -c -S -o.\objects\wmath.s --depend=.\objects\wmath.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\objects\wmath.crf cores\WMath.cpp]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i._Z10randomSeedj||, CODE, READONLY, ALIGN=1

_Z10randomSeedj PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CBZ      r4,|L0.12|
        MOV      r0,r4
        BL       srand
|L0.12|
        POP      {r4,pc}
        ENDP


        AREA ||i._Z6randoml||, CODE, READONLY, ALIGN=1

_Z6randoml PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CBNZ     r4,|L1.10|
        MOVS     r0,#0
|L1.8|
        POP      {r4,pc}
|L1.10|
        BL       rand
        SDIV     r1,r0,r4
        MLS      r0,r4,r1,r0
        B        |L1.8|
        ENDP


        AREA ||i._Z6randomll||, CODE, READONLY, ALIGN=1

_Z6randomll PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOV      r5,r1
        CMP      r4,r5
        BLT      |L2.14|
        MOV      r0,r4
|L2.12|
        POP      {r4-r6,pc}
|L2.14|
        SUBS     r6,r5,r4
        MOV      r0,r6
        BL       _Z6randoml
        ADD      r0,r0,r4
        B        |L2.12|
        ENDP


        AREA ||i._Z8makeWordhh||, CODE, READONLY, ALIGN=1

_Z8makeWordhh PROC
        MOV      r2,r0
        ORR      r0,r1,r2,LSL #8
        BX       lr
        ENDP


        AREA ||i._Z8makeWordt||, CODE, READONLY, ALIGN=1

_Z8makeWordt PROC
        BX       lr
        ENDP


        AREA ||.ARM.exidx||, LINKORDER=||i._Z10randomSeedj||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        DCD      0x00000000
        RELOC 42, ||i._Z10randomSeedj||
        DCD      0x00000001

        AREA ||area_number.6||, LINKORDER=||i._Z6randoml||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.6||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._Z6randoml||
        DCD      0x00000001

        AREA ||area_number.7||, LINKORDER=||i._Z6randomll||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.7||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._Z6randomll||
        DCD      0x00000001

        AREA ||area_number.8||, LINKORDER=||i._Z8makeWordt||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.8||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._Z8makeWordt||
        DCD      0x00000001

        AREA ||area_number.9||, LINKORDER=||i._Z8makeWordhh||, DATA, READONLY, SECTYPE={SHT_ARM_EXIDX}, ALIGN=2

        EXPORTAS ||area_number.9||, ||.ARM.exidx||
        DCD      0x00000000
        RELOC 42, ||i._Z8makeWordhh||
        DCD      0x00000001

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        EXPORT _Z10randomSeedj [CODE]
        EXPORT _Z6randoml [CODE]
        EXPORT _Z6randomll [CODE]
        EXPORT _Z8makeWordhh [CODE]
        EXPORT _Z8makeWordt [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT ||Lib$$Request$$cpplib|| [CODE,WEAK]
        IMPORT srand [CODE]
        IMPORT rand [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,6,0
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
