; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\wiring_time.s --depend=.\wiring_time.d --cpu=Cortex-M4.fp --apcs=interwork -O0 --diag_suppress=9931 -I.\cores -I.\libraries\Wire\src\utility -I.\libraries\SPI\src\utility -I.\libraries\SPI\src -I.\libraries\Wire\src -I.\cores\xmc_lib\LIBS -I..\test222 -I.\RTE\Device\XMC4700-F144x2048 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.1\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMC4700_series\Include -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\Device\XMClib\inc -IC:\Keil_v5\ARM\PACK\Infineon\XMC4000_DFP\2.9.1\RTE_Driver -D__MICROLIB -D__UVISION_VERSION=524 -D_RTE_ -DXMC4700_F144x2048 --omf_browse=.\wiring_time.crf cores\wiring_time.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.NOPS_FOR_USEC||, CODE, READONLY, ALIGN=1

NOPS_FOR_USEC PROC
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        NOP      
        BX       lr
        ENDP


        AREA ||i.SysTick_Handler||, CODE, READONLY, ALIGN=2

SysTick_Handler PROC
        PUSH     {r4,lr}
        LDR      r0,|L1.60|
        LDR      r4,[r0,#0]  ; g_timer_list
        LDR      r0,|L1.64|
        LDR      r0,[r0,#0]  ; g_systick_count
        ADDS     r0,r0,#1
        LDR      r1,|L1.64|
        STR      r0,[r1,#0]  ; g_systick_count
        CBZ      r4,|L1.56|
        LDR      r0,[r4,#0x18]
        CMP      r0,#1
        BLS      |L1.32|
        LDR      r0,[r4,#0x18]
        SUBS     r0,r0,#1
        STR      r0,[r4,#0x18]
        B        |L1.56|
|L1.32|
        MOVS     r0,#0
        STR      r0,[r4,#0x18]
        LDR      r0,|L1.68|
        LDRH     r0,[r0,#0]  ; g_timer_entered_handler
        CBNZ     r0,|L1.56|
        BL       XMC_SYSTIMER_lTimerHandler
        LDR      r0,|L1.68|
        LDRH     r0,[r0,#0]  ; g_timer_entered_handler
        SUBS     r0,r0,#1
        LDR      r1,|L1.68|
        STRH     r0,[r1,#0]
|L1.56|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L1.60|
        DCD      g_timer_list
|L1.64|
        DCD      g_systick_count
|L1.68|
        DCD      g_timer_entered_handler

        AREA ||i.XMC_SYSTIMER_CreateTimer||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_CreateTimer PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOVS     r0,#0
        MOVS     r1,#0
        MOVS     r6,#0
        CMP      r4,#0x3e8
        BCS      |L2.22|
        B        |L2.202|
|L2.22|
        MOVS     r1,#0
        B        |L2.196|
|L2.26|
        MOVS     r7,#1
        LSLS     r7,r7,r1
        LDR      r12,|L2.208|
        LDR      r12,[r12,#0]  ; g_timer_tracker
        AND      r7,r7,r12
        CBNZ     r7,|L2.168|
        MOVS     r7,#1
        LSLS     r7,r7,r1
        LDR      r12,|L2.208|
        LDR      r12,[r12,#0]  ; g_timer_tracker
        ORR      r7,r7,r12
        LDR      r12,|L2.208|
        STR      r7,[r12,#0]  ; g_timer_tracker
        ADD      r7,r1,r1,LSL #3
        LDR      r12,|L2.212|
        ADD      r7,r12,r7,LSL #2
        STR      r1,[r7,#0x14]
        ADD      r7,r1,r1,LSL #3
        ADD      r7,r12,r7,LSL #2
        STRB     r5,[r7,#0xc]
        MOVS     r7,#2
        ADD      r12,r1,r1,LSL #3
        LDR      r8,|L2.212|
        ADD      r12,r8,r12,LSL #2
        STRB     r7,[r12,#0xd]
        MOV      r7,#0x3e8
        UDIV     r6,r4,r7
        ADDS     r7,r6,#1
        ADD      r12,r1,r1,LSL #3
        ADD      r12,r8,r12,LSL #2
        STR      r7,[r12,#0x18]
        ADD      r7,r1,r1,LSL #3
        MOV      r12,r8
        ADD      r7,r12,r7,LSL #2
        STR      r6,[r7,#0x1c]
        ADD      r7,r1,r1,LSL #3
        ADD      r7,r12,r7,LSL #2
        STR      r2,[r7,#8]
        ADD      r7,r1,r1,LSL #3
        ADD      r7,r12,r7,LSL #2
        STR      r3,[r7,#0x10]
        MOVS     r7,#0
        B        |L2.170|
|L2.168|
        B        |L2.194|
|L2.170|
        ADD      r12,r1,r1,LSL #3
        ADD      r12,r8,r12,LSL #2
        STR      r7,[r12,#4]
        ADD      r12,r1,r1,LSL #3
        STR      r7,[r8,r12,LSL #2]
        ADDS     r0,r1,#1
        B        |L2.200|
|L2.194|
        ADDS     r1,r1,#1
|L2.196|
        CMP      r1,#8
        BCC      |L2.26|
|L2.200|
        NOP      
|L2.202|
        POP      {r4-r8,pc}
        ENDP

        DCW      0x0000
|L2.208|
        DCD      g_timer_tracker
|L2.212|
        DCD      g_timer_tbl

        AREA ||i.XMC_SYSTIMER_DeleteTimer||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_DeleteTimer PROC
        PUSH     {r4,lr}
        MOV      r1,r0
        MOVS     r0,#0
        SUBS     r2,r1,#1
        ADD      r2,r2,r2,LSL #3
        LDR      r3,|L3.100|
        ADD      r2,r3,r2,LSL #2
        LDRB     r2,[r2,#0xd]
        CBNZ     r2,|L3.26|
        MOVS     r0,#1
        B        |L3.96|
|L3.26|
        SUBS     r2,r1,#1
        ADD      r2,r2,r2,LSL #3
        LDR      r3,|L3.100|
        ADD      r2,r3,r2,LSL #2
        LDRB     r2,[r2,#0xd]
        CMP      r2,#2
        BNE      |L3.78|
        MOVS     r3,#0
        SUBS     r2,r1,#1
        ADD      r2,r2,r2,LSL #3
        LDR      r4,|L3.100|
        ADD      r2,r4,r2,LSL #2
        STRB     r3,[r2,#0xd]
        SUBS     r2,r1,#1
        MOVS     r3,#1
        LSLS     r3,r3,r2
        LDR      r2,|L3.104|
        LDR      r2,[r2,#0]  ; g_timer_tracker
        BICS     r2,r2,r3
        LDR      r3,|L3.104|
        STR      r2,[r3,#0]  ; g_timer_tracker
        B        |L3.96|
|L3.78|
        MOVS     r3,#1
        SUBS     r2,r1,#1
        ADD      r2,r2,r2,LSL #3
        LDR      r4,|L3.100|
        ADD      r2,r4,r2,LSL #2
        STRB     r3,[r2,#0x20]
|L3.96|
        POP      {r4,pc}
        ENDP

        DCW      0x0000
|L3.100|
        DCD      g_timer_tbl
|L3.104|
        DCD      g_timer_tracker

        AREA ||i.XMC_SYSTIMER_GetTickCount||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_GetTickCount PROC
        LDR      r0,|L4.8|
        LDR      r0,[r0,#0]  ; g_systick_count
        BX       lr
        ENDP

        DCW      0x0000
|L4.8|
        DCD      g_systick_count

        AREA ||i.XMC_SYSTIMER_GetTime||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_GetTime PROC
        LDR      r0,|L5.12|
        LDR      r0,[r0,#0]  ; g_systick_count
        MOV      r1,#0x3e8
        MULS     r0,r1,r0
        BX       lr
        ENDP

|L5.12|
        DCD      g_systick_count

        AREA ||i.XMC_SYSTIMER_GetTimerState||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_GetTimerState PROC
        MOV      r1,r0
        SUBS     r0,r1,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r2,|L6.20|
        ADD      r0,r2,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        BX       lr
        ENDP

        DCW      0x0000
|L6.20|
        DCD      g_timer_tbl

        AREA ||i.XMC_SYSTIMER_RestartTimer||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_RestartTimer PROC
        PUSH     {r4-r8,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOVS     r7,#0
        MOVS     r6,#0
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L7.96|
        ADD      r0,r1,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        CBNZ     r0,|L7.32|
        MOVS     r6,#1
        B        |L7.90|
|L7.32|
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L7.96|
        ADD      r0,r1,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        CMP      r0,#2
        BEQ      |L7.58|
        MOV      r0,r4
        BL       XMC_SYSTIMER_StopTimer
        MOV      r6,r0
|L7.58|
        CBNZ     r6,|L7.90|
        MOV      r0,#0x3e8
        UDIV     r7,r5,r0
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L7.96|
        ADD      r0,r1,r0,LSL #2
        STR      r7,[r0,#0x1c]
        MOV      r0,r4
        BL       XMC_SYSTIMER_StartTimer
        MOV      r6,r0
|L7.90|
        MOV      r0,r6
        POP      {r4-r8,pc}
        ENDP

|L7.96|
        DCD      g_timer_tbl

        AREA ||i.XMC_SYSTIMER_StartTimer||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_StartTimer PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#1
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L8.80|
        ADD      r0,r1,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        CMP      r0,#2
        BNE      |L8.74|
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        ADD      r0,r1,r0,LSL #2
        LDR      r0,[r0,#0x1c]
        ADDS     r0,r0,#1
        SUBS     r1,r4,#1
        ADD      r1,r1,r1,LSL #3
        LDR      r2,|L8.80|
        ADD      r1,r2,r1,LSL #2
        STR      r0,[r1,#0x18]
        MOVS     r1,#1
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        ADD      r0,r2,r0,LSL #2
        STRB     r1,[r0,#0xd]
        SUBS     r0,r4,#1
        BL       XMC_SYSTIMER_lInsertTimerList
        MOVS     r5,#0
|L8.74|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L8.80|
        DCD      g_timer_tbl

        AREA ||i.XMC_SYSTIMER_StopTimer||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_StopTimer PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r5,#0
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L9.72|
        ADD      r0,r1,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        CBNZ     r0,|L9.26|
        MOVS     r5,#1
        B        |L9.66|
|L9.26|
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r1,|L9.72|
        ADD      r0,r1,r0,LSL #2
        LDRB     r0,[r0,#0xd]
        CMP      r0,#1
        BNE      |L9.66|
        MOVS     r1,#2
        SUBS     r0,r4,#1
        ADD      r0,r0,r0,LSL #3
        LDR      r2,|L9.72|
        ADD      r0,r2,r0,LSL #2
        STRB     r1,[r0,#0xd]
        SUBS     r0,r4,#1
        BL       XMC_SYSTIMER_lRemoveTimerList
|L9.66|
        MOV      r0,r5
        POP      {r4-r6,pc}
        ENDP

        DCW      0x0000
|L9.72|
        DCD      g_timer_tbl

        AREA ||i.XMC_SYSTIMER_lInsertTimerList||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_lInsertTimerList PROC
        PUSH     {r4-r7,lr}
        MOVS     r3,#0
        ADD      r5,r0,r0,LSL #3
        LDR      r6,|L10.268|
        ADD      r5,r6,r5,LSL #2
        LDR      r4,[r5,#0x18]
        LDR      r5,|L10.272|
        LDR      r5,[r5,#0]  ; g_timer_list
        CBNZ     r5,|L10.36|
        ADD      r5,r0,r0,LSL #3
        ADD      r5,r6,r5,LSL #2
        LDR      r6,|L10.272|
        STR      r5,[r6,#0]  ; g_timer_list
        B        |L10.264|
|L10.36|
        LDR      r5,|L10.272|
        LDR      r1,[r5,#0]  ; g_timer_list
        MOV      r2,r4
        B        |L10.258|
|L10.44|
        LDR      r5,[r1,#0x18]
        SUBS     r2,r2,r5
        CMP      r2,#0
        BGT      |L10.214|
        LDR      r5,[r1,#4]
        CBZ      r5,|L10.106|
        ADD      r5,r0,r0,LSL #3
        LDR      r6,|L10.268|
        ADD      r5,r6,r5,LSL #2
        LDR      r6,[r1,#4]
        STR      r5,[r6,#0]
        ADD      r6,r0,r0,LSL #3
        LDR      r7,|L10.268|
        ADD      r6,r7,r6,LSL #2
        LDR      r5,[r1,#4]
        STR      r5,[r6,#4]
        ADD      r5,r0,r0,LSL #3
        MOV      r6,r7
        STR      r1,[r6,r5,LSL #2]
        ADD      r5,r0,r0,LSL #3
        ADD      r5,r6,r5,LSL #2
        STR      r5,[r1,#4]
        B        |L10.150|
|L10.106|
        LDR      r5,|L10.272|
        LDR      r5,[r5,#0]  ; g_timer_list
        ADD      r6,r0,r0,LSL #3
        LDR      r7,|L10.268|
        STR      r5,[r7,r6,LSL #2]
        ADD      r5,r0,r0,LSL #3
        MOV      r6,r7
        ADD      r5,r6,r5,LSL #2
        LDR      r6,|L10.272|
        LDR      r6,[r6,#0]  ; g_timer_list
        STR      r5,[r6,#4]
        ADD      r5,r0,r0,LSL #3
        MOV      r6,r7
        ADD      r5,r6,r5,LSL #2
        LDR      r6,|L10.272|
        STR      r5,[r6,#0]  ; g_timer_list
|L10.150|
        ADD      r5,r0,r0,LSL #3
        LDR      r6,|L10.268|
        LDR      r5,[r6,r5,LSL #2]
        LDR      r5,[r5,#0x18]
        ADD      r5,r5,r2
        ADD      r6,r0,r0,LSL #3
        LDR      r7,|L10.268|
        ADD      r6,r7,r6,LSL #2
        STR      r5,[r6,#0x18]
        ADD      r5,r0,r0,LSL #3
        MOV      r6,r7
        LDR      r5,[r6,r5,LSL #2]
        LDR      r5,[r5,#0x18]
        ADD      r6,r0,r0,LSL #3
        ADD      r6,r7,r6,LSL #2
        LDR      r6,[r6,#0x18]
        SUBS     r5,r5,r6
        ADD      r6,r0,r0,LSL #3
        LDR      r6,[r7,r6,LSL #2]
        STR      r5,[r6,#0x18]
        MOVS     r3,#1
        B        |L10.256|
|L10.214|
        CMP      r2,#0
        BLE      |L10.256|
        LDR      r5,[r1,#0]
        CBNZ     r5,|L10.256|
        ADD      r5,r0,r0,LSL #3
        LDR      r6,|L10.268|
        ADD      r5,r6,r5,LSL #2
        STR      r1,[r5,#4]
        ADD      r5,r0,r0,LSL #3
        ADD      r5,r6,r5,LSL #2
        STR      r5,[r1,#0]
        ADD      r5,r0,r0,LSL #3
        ADD      r5,r6,r5,LSL #2
        STR      r2,[r5,#0x18]
        MOVS     r3,#1
|L10.256|
        LDR      r1,[r1,#0]
|L10.258|
        CBZ      r1,|L10.264|
        CMP      r3,#0
        BEQ      |L10.44|
|L10.264|
        POP      {r4-r7,pc}
        ENDP

        DCW      0x0000
|L10.268|
        DCD      g_timer_tbl
|L10.272|
        DCD      g_timer_list

        AREA ||i.XMC_SYSTIMER_lRemoveTimerList||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_lRemoveTimerList PROC
        MOV      r1,r0
        ADD      r2,r1,r1,LSL #3
        LDR      r3,|L11.112|
        ADD      r0,r3,r2,LSL #2
        LDR      r2,[r0,#4]
        CBNZ     r2,|L11.28|
        LDR      r2,[r0,#0]
        CBNZ     r2,|L11.28|
        MOVS     r2,#0
        LDR      r3,|L11.116|
        STR      r2,[r3,#0]  ; g_timer_list
        B        |L11.110|
|L11.28|
        LDR      r2,[r0,#4]
        CBNZ     r2,|L11.66|
        LDR      r3,|L11.116|
        LDR      r2,[r0,#0]
        STR      r2,[r3,#0]  ; g_timer_list
        MOVS     r2,#0
        LDR      r3,[r3,#0]  ; g_timer_list
        STR      r2,[r3,#4]
        LDR      r2,|L11.116|
        LDR      r2,[r2,#0]  ; g_timer_list
        LDR      r2,[r2,#0x18]
        LDR      r3,[r0,#0x18]
        ADD      r2,r2,r3
        LDR      r3,|L11.116|
        LDR      r3,[r3,#0]  ; g_timer_list
        STR      r2,[r3,#0x18]
        MOVS     r2,#0
        STR      r2,[r0,#0]
        B        |L11.110|
|L11.66|
        LDR      r2,[r0,#0]
        CBNZ     r2,|L11.80|
        MOVS     r2,#0
        LDR      r3,[r0,#4]
        STR      r2,[r3,#0]
        STR      r2,[r0,#4]
        B        |L11.110|
|L11.80|
        LDRD     r2,r3,[r0,#0]
        STR      r2,[r3,#0]
        LDRD     r3,r2,[r0,#0]
        STR      r2,[r3,#4]
        LDR      r2,[r0,#0]
        LDR      r2,[r2,#0x18]
        LDR      r3,[r0,#0x18]
        ADD      r2,r2,r3
        LDR      r3,[r0,#0]
        STR      r2,[r3,#0x18]
        MOVS     r2,#0
        STR      r2,[r0,#0]
        STR      r2,[r0,#4]
|L11.110|
        BX       lr
        ENDP

|L11.112|
        DCD      g_timer_tbl
|L11.116|
        DCD      g_timer_list

        AREA ||i.XMC_SYSTIMER_lTimerHandler||, CODE, READONLY, ALIGN=2

XMC_SYSTIMER_lTimerHandler PROC
        PUSH     {r4,lr}
        LDR      r0,|L12.136|
        LDRH     r0,[r0,#0]  ; g_timer_entered_handler
        ADDS     r0,r0,#1
        LDR      r1,|L12.136|
        STRH     r0,[r1,#0]
        LDR      r0,|L12.140|
        LDR      r4,[r0,#0]  ; g_timer_list
        B        |L12.124|
|L12.18|
        LDRB     r0,[r4,#0x20]
        CMP      r0,#1
        BNE      |L12.54|
        LDR      r0,[r4,#0x14]
        BL       XMC_SYSTIMER_lRemoveTimerList
        MOVS     r0,#0
        STRB     r0,[r4,#0xd]
        LDRB     r1,[r4,#0x14]
        MOVS     r0,#1
        LSLS     r0,r0,r1
        LDR      r1,|L12.144|
        LDR      r1,[r1,#0]  ; g_timer_tracker
        BICS     r1,r1,r0
        LDR      r0,|L12.144|
        STR      r1,[r0,#0]  ; g_timer_tracker
        B        |L12.120|
|L12.54|
        LDRB     r0,[r4,#0xc]
        CBNZ     r0,|L12.82|
        LDRB     r0,[r4,#0xd]
        CMP      r0,#1
        BNE      |L12.120|
        LDR      r0,[r4,#0x14]
        BL       XMC_SYSTIMER_lRemoveTimerList
        MOVS     r0,#2
        STRB     r0,[r4,#0xd]
        LDR      r1,[r4,#8]
        LDR      r0,[r4,#0x10]
        BLX      r1
        B        |L12.120|
|L12.82|
        LDRB     r0,[r4,#0xc]
        CMP      r0,#1
        BNE      |L12.118|
        LDRB     r0,[r4,#0xd]
        CMP      r0,#1
        BNE      |L12.120|
        LDR      r0,[r4,#0x14]
        BL       XMC_SYSTIMER_lRemoveTimerList
        LDR      r0,[r4,#0x1c]
        STR      r0,[r4,#0x18]
        LDR      r0,[r4,#0x14]
        BL       XMC_SYSTIMER_lInsertTimerList
        LDR      r1,[r4,#8]
        LDR      r0,[r4,#0x10]
        BLX      r1
        B        |L12.120|
|L12.118|
        B        |L12.132|
|L12.120|
        LDR      r0,|L12.140|
        LDR      r4,[r0,#0]  ; g_timer_list
|L12.124|
        CBZ      r4,|L12.132|
        LDR      r0,[r4,#0x18]
        CMP      r0,#0
        BEQ      |L12.18|
|L12.132|
        NOP      
        POP      {r4,pc}
        ENDP

|L12.136|
        DCD      g_timer_entered_handler
|L12.140|
        DCD      g_timer_list
|L12.144|
        DCD      g_timer_tracker

        AREA ||i.__NVIC_SetPriority||, CODE, READONLY, ALIGN=2

__NVIC_SetPriority PROC
        PUSH     {r4,lr}
        CMP      r0,#0
        BLT      |L13.16|
        LSLS     r2,r1,#26
        LSRS     r3,r2,#24
        LDR      r2,|L13.32|
        STRB     r3,[r2,r0]
        B        |L13.30|
|L13.16|
        LSLS     r2,r1,#26
        LSRS     r4,r2,#24
        LDR      r2,|L13.36|
        AND      r3,r0,#0xf
        SUBS     r3,r3,#4
        STRB     r4,[r2,r3]
|L13.30|
        POP      {r4,pc}
        ENDP

|L13.32|
        DCD      0xe000e400
|L13.36|
        DCD      0xe000ed18

        AREA ||i.delay||, CODE, READONLY, ALIGN=2

delay PROC
        PUSH     {r4-r6,lr}
        MOV      r4,r0
        MOVS     r0,#0
        LDR      r1,|L14.56|
        STRB     r0,[r1,#0]
        MOV      r1,#0x3e8
        MUL      r0,r4,r1
        MOVS     r3,#0
        LDR      r2,|L14.60|
        MOV      r1,r3
        BL       XMC_SYSTIMER_CreateTimer
        MOV      r5,r0
        CBZ      r5,|L14.54|
        MOV      r0,r5
        BL       XMC_SYSTIMER_StartTimer
        NOP      
|L14.40|
        LDR      r0,|L14.56|
        LDRB     r0,[r0,#0]  ; delay_timer_expired
        CMP      r0,#0
        BEQ      |L14.40|
        MOV      r0,r5
        BL       XMC_SYSTIMER_DeleteTimer
|L14.54|
        POP      {r4-r6,pc}
        ENDP

|L14.56|
        DCD      delay_timer_expired
|L14.60|
        DCD      delay_cb

        AREA ||i.delay_cb||, CODE, READONLY, ALIGN=2

delay_cb PROC
        MOVS     r1,#1
        LDR      r2,|L15.8|
        STRB     r1,[r2,#0]
        BX       lr
        ENDP

|L15.8|
        DCD      delay_timer_expired

        AREA ||i.micros||, CODE, READONLY, ALIGN=1

micros PROC
        PUSH     {lr}
        BL       XMC_SYSTIMER_GetTime
        POP      {pc}
        ENDP


        AREA ||i.millis||, CODE, READONLY, ALIGN=1

millis PROC
        PUSH     {lr}
        BL       XMC_SYSTIMER_GetTime
        MOV      r1,#0x3e8
        UDIV     r0,r0,r1
        POP      {pc}
        ENDP


        AREA ||i.wiring_time_init||, CODE, READONLY, ALIGN=2

wiring_time_init PROC
        PUSH     {r4,lr}
        MOVS     r0,#0
        LDR      r1,|L18.68|
        STR      r0,[r1,#0]  ; g_timer_list
        LDR      r4,|L18.72|
        SUBS     r0,r4,#1
        CMP      r0,#0x1000000
        BCC      |L18.20|
        B        |L18.52|
|L18.20|
        SUBS     r0,r4,#1
        MOV      r1,#0xe000e000
        STR      r0,[r1,#0x14]
        MOVS     r1,#0x3f
        MOV      r0,#0xffffffff
        BL       __NVIC_SetPriority
        MOVS     r0,#0
        MOV      r1,#0xe000e000
        STR      r0,[r1,#0x18]
        MOVS     r0,#7
        STR      r0,[r1,#0x10]
        NOP      
|L18.52|
        MOVS     r1,#4
        SUBS     r0,r1,#5
        BL       __NVIC_SetPriority
        MOVS     r0,#0
        LDR      r1,|L18.76|
        STR      r0,[r1,#0]  ; g_timer_tracker
        POP      {r4,pc}
        ENDP

|L18.68|
        DCD      g_timer_list
|L18.72|
        DCD      0x00023280
|L18.76|
        DCD      g_timer_tracker

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.bss||, DATA, NOINIT, ALIGN=2

g_timer_tbl
        %        288

        AREA ||.data||, DATA, ALIGN=2

g_timer_list
        DCD      0x00000000
g_timer_tracker
        DCD      0x00000000
g_timer_entered_handler
        DCW      0x0000
        DCB      0x00,0x00
g_systick_count
        DCD      0x00000000
delay_timer_expired
        DCB      0x00

;*** Start embedded assembler ***

#line 1 "cores\\wiring_time.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___13_wiring_time_c_dbd866df____REV16|
#line 447 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.1\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___13_wiring_time_c_dbd866df____REV16| PROC
#line 448

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___13_wiring_time_c_dbd866df____REVSH|
#line 462
|__asm___13_wiring_time_c_dbd866df____REVSH| PROC
#line 463

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___13_wiring_time_c_dbd866df____RRX|
#line 649
|__asm___13_wiring_time_c_dbd866df____RRX| PROC
#line 650

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT NOPS_FOR_USEC [CODE]
        EXPORT SysTick_Handler [CODE]
        EXPORT XMC_SYSTIMER_CreateTimer [CODE]
        EXPORT XMC_SYSTIMER_DeleteTimer [CODE]
        EXPORT XMC_SYSTIMER_GetTickCount [CODE]
        EXPORT XMC_SYSTIMER_GetTime [CODE]
        EXPORT XMC_SYSTIMER_GetTimerState [CODE]
        EXPORT XMC_SYSTIMER_RestartTimer [CODE]
        EXPORT XMC_SYSTIMER_StartTimer [CODE]
        EXPORT XMC_SYSTIMER_StopTimer [CODE]
        EXPORT delay [CODE]
        EXPORT delay_cb [CODE]
        EXPORT micros [CODE]
        EXPORT millis [CODE]
        EXPORT wiring_time_init [CODE]
        EXPORT g_timer_tbl [DATA,SIZE=288]
        EXPORT g_timer_list [DATA,SIZE=4]
        EXPORT g_timer_tracker [DATA,SIZE=4]
        EXPORT g_timer_entered_handler [DATA,SIZE=2]
        EXPORT g_systick_count [DATA,SIZE=4]
        EXPORT delay_timer_expired [DATA,SIZE=1]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        KEEP XMC_SYSTIMER_lInsertTimerList
        KEEP XMC_SYSTIMER_lRemoveTimerList
        KEEP XMC_SYSTIMER_lTimerHandler
        KEEP __NVIC_SetPriority

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
